version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php82
    ports:
      - 82:80
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql:8.0
    container_name: mysql80
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cinema_v2
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
    volumes:
        - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
    ports:
        - 8888:80


        